/*
================
SYS_APPLICATIONS
================
*/

CREATE TABLE SYS_APPLICATIONS
(
   APPL_ID             NUMBER,
   APPL_SHORT_NAME     VARCHAR2 (30),
   APPL_NAME           VARCHAR2 (100),
   APPL_DESCRIPTION    VARCHAR2 (100),
   LAST_UPDATE_DATE    DATE NOT NULL,
   LAST_UPDATED_BY     NUMBER (15) NOT NULL,
   CREATION_DATE       DATE NOT NULL,
   CREATED_BY          NUMBER (15) NOT NULL,
   ENABLED_FLAG        VARCHAR2 (1) NOT NULL,
   START_DATE_ACTIVE   DATE,
   END_DATE_ACTIVE     DATE,
   ATTRIBUTE1          VARCHAR2 (150 BYTE),
   ATTRIBUTE2          VARCHAR2 (150 BYTE),
   ATTRIBUTE3          VARCHAR2 (150 BYTE),
   ATTRIBUTE4          VARCHAR2 (150 BYTE),
   ATTRIBUTE5          VARCHAR2 (150 BYTE),
   ATTRIBUTE6          VARCHAR2 (150 BYTE),
   ATTRIBUTE7          VARCHAR2 (150 BYTE),
   ATTRIBUTE8          VARCHAR2 (150 BYTE),
   ATTRIBUTE9          VARCHAR2 (150 BYTE),
   ATTRIBUTE10         VARCHAR2 (150 BYTE)
);

CREATE SEQUENCE SYS_APPLICATIONS_S
   START WITH 1
   MAXVALUE 9999999999999999999999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;

CREATE OR REPLACE TRIGGER SYS_APPLICATIONS_BI
   BEFORE INSERT
   ON SYS_APPLICATIONS
   FOR EACH ROW
BEGIN
   SELECT SYS_APPLICATIONS_S.NEXTVAL INTO :new.APPL_ID:new.APPL_ID FROM DUAL;
   :new.START_DATE_ACTIVE := SYSDATE;
END;
/
/*
==========
FND_USERS
==========
*/

CREATE TABLE FND_USERS
(
   USER_ID                   NUMBER,
   USER_NAME                 VARCHAR2 (100) NOT NULL,
   USER_FNAME                VARCHAR2 (30) NOT NULL,
   USER_MNAME                VARCHAR2 (30) NOT NULL,
   USER_LNAME                VARCHAR2 (30) NOT NULL,
   USER_DESCRIPTION          VARCHAR2 (255),
   USER_EMP_ID               NUMBER (15),
   USER_EMAIL                VARCHAR2 (240 BYTE),
   USER_PHONE_CODE           NUMBER,
   USER_PHONE_NUMBER         NUMBER,
   USER_PHONE_EXT            NUMBER,
   USER_FAX_CODE             NUMBER,
   USER_FAX_NUMBER           NUMBER,
   MANAGER_ID                NUMBER,
   LAST_UPDATE_DATE          DATE NOT NULL,
   LAST_UPDATED_BY           NUMBER (15) NOT NULL,
   CREATION_DATE             DATE NOT NULL,
   CREATED_BY                NUMBER (15) NOT NULL,
   ENABLED_FLAG              VARCHAR2 (1) NOT NULL,
   START_DATE_ACTIVE         DATE,
   END_DATE_ACTIVE           DATE,
   ENCRYPTED_USER_PASSWORD   VARCHAR2 (100) NOT NULL,
   LAST_LOGON_DATE           DATE,
   PASSWORD_DATE             DATE
);

CREATE SEQUENCE FND_USERS_S
   START WITH 1
   MAXVALUE 9999999999999999999999999999
   MINVALUE 1
   NOCYCLE
   NOCACHE
   NOORDER;

CREATE OR REPLACE TRIGGER FND_USERS_BI
   BEFORE INSERT
   ON FND_USERS
   FOR EACH ROW
BEGIN
   SELECT FND_USERS_S.NEXTVAL INTO :new.USER_ID FROM DUAL;
   :new.START_DATE_ACTIVE := SYSDATE;
END;
/
SHOW ERRORS;
